// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/tetsuyaohta/go-backend-boilerplate/ent/runtime.go

const (
	Version = "v0.14.4"                                         // Version of ent codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent codegen.
)
