// +build ignore

package main

import (
	"log"
	"os"
	"path/filepath"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	// Get the current working directory
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal("failed to get current directory:", err)
	}

	// Construct absolute paths
	schemaPath := filepath.Join(cwd, "ent", "schema")
	targetPath := filepath.Join(cwd, "ent")

	// Ensure the schema directory exists
	if _, err := os.Stat(schemaPath); os.IsNotExist(err) {
		log.Fatalf("schema directory not found: %s", schemaPath)
	}

	if err := entc.Generate(schemaPath, &gen.Config{
		Target:  targetPath,
		Package: "github.com/tetsuyaohta/go-backend-boilerplate/ent",
		Header:  "// Code generated by entc, DO NOT EDIT.",
	}); err != nil {
		log.Fatal("running entc:", err)
	}
}